// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// load .env file
import "dotenv/config";
// import prisma confi helper
import { defineConfig } from "prisma/config";

export default defineConfig({
  //prisma schema file location
  schema: "prisma/schema.prisma",
  // store migration file here
  migrations: {
    path: "prisma/migrations",
  },
  // read dbcon from .env
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
